### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by ihorMatey**

### CODE REVIEW

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
1

**Review by AlinaMatuschak — CHANGES_REQUESTED** [review]
dwefe

**Review by AlinaMatuschak — CHANGES_REQUESTED** [review]
hkfrf

**Review by matuschak90565 — CHANGES_REQUESTED** [review]
hguoi

**Review by ihorMate — CHANGES_REQUESTED** [review]
123

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
1

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
1

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
1

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
1

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
1

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — APPROVED** [review]
1

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
1

**Review by ihor-jpeg — APPROVED** [review]

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — APPROVED** [review]

**Review by ihor-jpeg — APPROVED** [review]

**Review by ihorMate — APPROVED** [review]
1

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
1

**Review by ihor-jpeg — APPROVED** [review]

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Pull request closed without merging**
