### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by ihorMatey**

### CODE REVIEW

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
1

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1111

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — APPROVED** [review]
1

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
21212

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
1

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
1

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
1

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihor-jpeg — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by matuschak90565 — CHANGES_REQUESTED** [review]
nkoi

**Review by matuschak90565 — CHANGES_REQUESTED** [review]
do something 💩

**Review by matuschak90565 — CHANGES_REQUESTED** [review]
🤯

**Review by matuschak90565 — CHANGES_REQUESTED** [review]
🤢

**Review by matuschak90565 — APPROVED** [review]
✅

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — CHANGES_REQUESTED** [review]
1

**Review by ihorMate — APPROVED** [review]

**Review by ihor-jpeg — APPROVED** [review]

**Pull request closed without merging**
